feat(docker): create telos image
edenia/telos-local pull request #1
Opened 2021-10-14 15:35 UTC by leisterfrancisco

## What does this PR do?
- Clone Telos contract to build it
- Set eosio.cdt and eosio version according to Telos [release/1.6.x](https://github.com/telosnetwork/telos.contracts/tree/release/1.6.x) dependencies specifications
- Set staring script

Waiting for answer in [telosnetwork/telos.contracts](https://github.com/telosnetwork/telos.contracts/issues/19) on a reported issue

2021-11-07 13:01 UTC, leisterfrancisco commented on README.md
>  # Telos Mainnet Local Network
I don't feel it is a good name, what do you think @xavier506?

2021-11-08 17:25 UTC, xavier506 commented on .github/workflows/publish-docker-image.yaml
> +          TESTNET_EOSIO_PRIVATE_KEY: ${{ secrets.TESTNET_EOSIO_PRIVATE_KEY }}
@leisterfrancisco do we need these as repo secrets or in .env?

2021-11-08 18:16 UTC, xavier506 requested changes
@leisterfrancisco  please see my comments

can wee add a note about the system contracts on the readme file also

2021-11-08 18:16 UTC, xavier506 commented on README.md
>  # Telos Mainnet Local Network
Telos Local Development Network?

2021-11-09 18:41 UTC, leisterfrancisco commented on README.md
> +## Note
@xavier506 what do you think?

2021-11-09 20:51 UTC, xavier506 commented on README.md
> +## Note
perfect!

2021-11-10 17:13 UTC, merged